architecture: OVDETR
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True


OVDETR:
  backbone: ResNet
  neck: ChannelMapper
  encoder: OVDeformableTransformerEncoder
  decoder: OVDeformableTransformerDecoder
  position_embedding: PositionEmbedding
  detr_head: OVDeformableDETRHead
  two_stage: True
  with_box_refine: True
  post_process: DETRBBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4

ChannelMapper:
  backbone_num_channels: [512, 1024, 2048]

OVDeformableTransformerEncoder:
  hidden_dim: 256
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
  num_feature_levels: 4
  num_encoder_points: 4
  num_layers: 6

OVDeformableTransformerDecoder:
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
  num_feature_levels: 4
  num_decoder_points: 4
  num_layers: 6
  cls_out_channels: 2
  num_mlp_layers: 3
  return_intermediate: True
  with_box_refine: True

PositionEmbedding:
  offset: -0.5

OVDeformableDETRHead:
  num_mlp_layers: 3


OVDETRLoss:
  loss_coeff: {class: 2, bbox: 5, giou: 2, mask: 1, dice: 1}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 2, bbox: 5, giou: 2}
