architecture: OVDETR
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True


OVDETR:
  backbone: ResNet
  neck: DETRChannelMapper
  transformer: OVDeformableTransformer
  detr_head: OVDeformableDETRHead
  max_len: 6
  prob: 0.5
  two_stage: True
  with_box_refine: True
  post_process: OVDETRBBoxPostProcess
  bpe_path: /home/a401-2/PycharmProjects/PaddleDetection/ppdet/modeling/embedder/clip/bpe_simple_vocab_16e6.txt.gz
  clip_feat_path: /home/a401-2/PycharmProjects/PaddleDetection/ppdet/modeling/transformers/clip_feat_coco_pickle_label.pkl


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4

DETRChannelMapper:
  num_feature_levels: 4

OVDeformableTransformer:
  nhead: 8
  dropout: 0.1


OVDeformableDETRHead:
  num_mlp_layers: 3
  cls_out_channels: 1


OVDETRLoss:
  loss_coeff: {class: 3, bbox: 5, giou: 2, embed: 2}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 3, bbox: 5, giou: 2}

OVHungarianMatcher:
  matcher_coeff: {class: 3, bbox: 5, giou: 2}
