metric: ZeroshotCOCO
num_classes: 91

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: zero-shot/instances_train2017_seen_2_proposal.json
    dataset_dir: dataset/zeroshot_coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: zero-shot/instances_val2017_all_2.json
    dataset_dir: dataset/zeroshot_coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: zero-shot/instances_val2017_all_2.json
    dataset_dir: dataset/zeroshot_coco # if set, anno_path will be 'dataset_dir/anno_path'
